language : java

addons:
  sonarcloud:
    organization: "your-sonar-organization-name"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=carole_ipi-java-350-ex